apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: reviews
data:
  MYSQL_USER: "romman"
  MYSQL_DATABASE: "Reviews"
  MYSQL_HOST: "reviews-mysql-ss-0.mysql-svc.default.svc.cluster.local"
