apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  labels:
    app: reviews
type: Opaque
data:
  MYSQL_PASSWORD: cm9tbWFu #romman
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA== #root_password
