apiVersion: v1
kind: Service
metadata:
  name: reviews-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: reviews
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 5000 # Port on the Pods
