apiVersion: v1
kind: ConfigMap
metadata:
  name: reviews-config
  labels:
    app: reviews
data:
  DB_HOST: mysql-ss-0.mysql-svc.default.svc.cluster.local #needs to be edited
  MYSQL_USER: "romman"
  MYSQL_DATABASE: "Namesdb"
  MYSQL_URL: mysql://$(MYSQL_USER):$(MYSQL_PASSWORD)@$(DB_HOST):3307/$(MYSQL_DATABASE)
