apiVersion: v1
kind: ConfigMap
metadata:
  name: reviews-config
  labels:
    app: reviews
data:
  MYSQL_USER: "romman"
  MYSQL_DATABASE: "Reviews"
  MYSQL_HOST: reviews-mysql-ss-0.mysql-svc.default.svc.cluster.local #needs to be edited
  MYSQL_URL: mysql://romman:romman@reviews-mysql-ss-0.mysql-svc.default.svc.cluster.local:3307/Reviews
